version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=local_db
    volumes:
      - docker-mysql:/var/lib/mysql
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin
    image: wilds/phpmyadmin:4.0.10.15
    hostname: phpmyadmin
    ports:
      - "8080:80"
    restart: on-failure
    links:
      - mysql:db

  vsftpd:
    container_name: vsftpd
    image: wilds/vsftpd
    hostname: vsftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - docker-html:/home/virtual/www-data/html
      - docker-certificates:/home/virtual/certs/certs
      - docker-mysql:/home/virtual/mysql/mysql
    environment:
      PASV_ADDRESS: 10.0.75.1
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30009
      VSFTPD_USER_1: 'www-data:ftp:33:'
      VSFTPD_USER_2: 'mysql:mysql:999:'
      VSFTPD_USER_3: 'certs:certs:50:'

  wordpress:
    container_name: wordpress
    image: wilds/wpdevenvironment:latest
    hostname: wordpress
    environment:
      - TIMEZONE=America/New_York
      - XDEBUG_REMOTE_HOST=10.0.75.1
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - docker-html:/var/www/html
      - docker-certificates:/usr/local/share/ca-certificates
    links:
      - mysql:db
    restart: on-failure

volumes:
  docker-mysql:
    external: true
  docker-html:
    external: true
  docker-certificates:
    external: true